/** Content + layout data for the Cosmos clone (coordinates are frame px from reference-dom/09.json). */

export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

/** A tilted floating image tile: centre (x, y), size and rotation in degrees. */
export interface FloatingTile {
  x: number
  y: number
  w: number
  h: number
  r: number
}

export const nav = {
  links: ['Explore', 'Sequence', 'Shop', 'Careers'],
  searchHint: 'Try',
  searchExample: "'women in history'",
  login: 'Log in',
  signup: 'Sign up',
}

export const hero = {
  wordmark: 'COSMOS',
  title: ['Your space', 'for inspiration'],
  primary: 'Sign up',
  secondary: 'Get the app',
}

/** Tiles drifting over the hero canvas (y relative to the hero top). */
export const heroTiles: FloatingTile[] = [
  { x: 1074, y: 68, w: 63, h: 91, r: 44 },
  { x: 688, y: 100, w: 43, h: 56, r: 0 },
  { x: 226, y: 131, w: 88, h: 70, r: 40 },
  { x: 1365, y: 147, w: 103, h: 69, r: 64 },
  { x: 508, y: 141, w: 84, h: 56, r: 64 },
  { x: 868, y: 145, w: 55, h: 83, r: 28 },
  { x: 8, y: 196, w: 44, h: 73, r: 20 },
  { x: 1189, y: 217, w: 66, h: 88, r: 62 },
  { x: 363, y: 259, w: 86, h: 57, r: 38 },
  { x: 1004, y: 269, w: 54, h: 81, r: 56 },
  { x: 129, y: 295, w: 98, h: 65, r: 22 },
  { x: 1412, y: 332, w: 57, h: 39, r: 84 },
  { x: 1245, y: 398, w: 48, h: 60, r: 82 },
  { x: 284, y: 427, w: 56, h: 45, r: 14 },
  { x: 87, y: 481, w: 57, h: 57, r: 4 },
  { x: 1412, y: 520, w: 50, h: 76, r: 0 },
  { x: 1236, y: 587, w: 93, h: 62, r: 14 },
  { x: 282, y: 614, w: 61, h: 82, r: 78 },
  { x: 1037, y: 639, w: 39, h: 85, r: 56 },
  { x: 103, y: 671, w: 80, h: 80, r: 76 },
  { x: 1393, y: 709, w: 89, h: 75, r: 18 },
  { x: 556, y: 733, w: 55, h: 68, r: 40 },
  { x: 901, y: 756, w: 77, h: 52, r: 60 },
  { x: 1160, y: 760, w: 91, h: 61, r: 34 },
  { x: 356, y: 785, w: 59, h: 88, r: 54 },
  { x: 724, y: 799, w: 38, h: 51, r: 2 },
  { x: 174, y: 848, w: 66, h: 100, r: 60 },
  { x: 1307, y: 878, w: 51, h: 68, r: 34 },
  { x: 1028, y: 885, w: 61, h: 50, r: 30 },
  { x: 20, y: 895, w: 50, h: 40, r: 20 },
  { x: 500, y: 895, w: 50, h: 40, r: 30 },
]

/** Tiles drifting in the closing CTA canvas (y relative to the CTA top at 4177). */
export const ctaTiles: FloatingTile[] = [
  { x: 198, y: 25, w: 77, h: 51, r: 28 },
  { x: 390, y: 10, w: 64, h: 45, r: 30 },
  { x: 603, y: 21, w: 53, h: 41, r: 72 },
  { x: 733, y: 15, w: 40, h: 40, r: 6 },
  { x: 1002, y: 12, w: 48, h: 40, r: 30 },
  { x: 1323, y: 21, w: 46, h: 87, r: 86 },
  { x: 858, y: 55, w: 42, h: 28, r: 36 },
  { x: 1199, y: 73, w: 55, h: 68, r: 68 },
  { x: 28, y: 87, w: 71, h: 56, r: 18 },
  { x: 488, y: 86, w: 42, h: 30, r: 46 },
  { x: 310, y: 105, w: 36, h: 46, r: 28 },
  { x: 1073, y: 123, w: 45, h: 68, r: 68 },
  { x: 1362, y: 143, w: 54, h: 80, r: 80 },
  { x: 145, y: 154, w: 55, h: 37, r: 16 },
  { x: 942, y: 158, w: 50, h: 45, r: 70 },
  { x: 415, y: 199, w: 46, h: 60, r: 70 },
  { x: 1232, y: 208, w: 54, h: 67, r: 84 },
  { x: 10, y: 225, w: 19, h: 43, r: 0 },
  { x: 267, y: 236, w: 64, h: 51, r: 10 },
  { x: 1100, y: 256, w: 44, h: 66, r: 88 },
  { x: 1373, y: 283, w: 38, h: 57, r: 10 },
  { x: 125, y: 293, w: 76, h: 52, r: 4 },
  { x: 396, y: 315, w: 56, h: 30, r: 0 },
]

export const worldSection = {
  title: 'Every search opens a new world.',
  panel: { x: 65, y: 1151, w: 1300, h: 420 } satisfies Rect,
  images: [
    { x: 140, y: 1163, w: 316, h: 395 },
    { x: 589, y: 1213, w: 237, h: 296 },
    { x: 974, y: 1167, w: 309, h: 387 },
  ] satisfies Rect[],
  query: 'future home',
  search: { x: 508, y: 1334, w: 414, h: 54 } satisfies Rect,
  caption: ['Your collections, your references, your', 'taste. Connected, searchable, yours.'],
}

export interface ToolCard {
  caption: string
  background?: string
  /** Image regions relative to the card's top-left. */
  images: Rect[]
  kind: 'color' | 'similar' | 'ai'
}

export const thinkSection = {
  title: 'Search the way you think.',
  cards: [
    {
      caption: 'By color',
      kind: 'color',
      images: [
        { x: 0, y: 19, w: 191, h: 411 },
        { x: 227, y: 67, w: 173, h: 318 },
      ],
    },
    {
      caption: 'by visual similarity',
      kind: 'similar',
      images: [
        { x: 0, y: 0, w: 223, h: 145 },
        { x: 272, y: 4, w: 128, h: 237 },
        { x: 0, y: 185, w: 157, h: 265 },
        { x: 213, y: 280, w: 187, h: 170 },
      ],
    },
    {
      caption: 'and without AI.',
      kind: 'ai',
      images: [{ x: 0, y: 0, w: 400, h: 450 }],
    },
  ] satisfies ToolCard[],
  colorChip: '#BC361B',
  ai: {
    title: 'AI content',
    body: 'Content detected as likely generated by AI',
    options: ['Show', 'Blur', 'Hide'],
  },
}

export const knowSection = {
  title: ['Know what', 'you’re', 'looking at.'],
  credit: 'Editorial photography by',
  creditName: 'Guiri',
  body: ['Cosmos researches', 'images—surfacing the', 'artist, source, and story.'],
}

export const teamsSection = {
  title: 'Inspiration for the world’s top creative teams.',
  /** Logo strip rows: first slot x and the visible slot count; each logo box is 100×60 on a 120px pitch. */
  rows: [
    { y: 3737, startX: 185, count: 9 },
    { y: 3817, startX: 195, count: 9 },
  ],
}

export const ctaSection = {
  lead: 'Dream with us.',
  button: 'Sign up for Cosmos',
}
